name: DAST Scan with Wapiti

on:
  push:
    branches:
      - main

jobs:
  wapiti-scan:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check if Wapiti is installed
        run: |
          - name: Check if Wapiti is installed
  run: |
    $wapitiPath = Get-Command wapiti -ErrorAction SilentlyContinue
    if (-Not $wapitiPath) {
      Write-Output "Wapiti is not installed. Installing now..."
      choco install wapiti
    } else {
      Write-Output "Wapiti is already installed at $($wapitiPath.Path)"
    }


      - name: Run Wapiti Scan
        run: wapiti -u http://localhost -o ./wapiti_report

      - name: Upload Wapiti Report
        uses: actions/upload-artifact@v2
        with:
          name: wapiti_report
          path: ./wapiti_report
